Repository SDOS-Winter2021/Team_13_speedywash, pull requests merged in 2021-04, with the labels that each got.

#52 Fixed #12 #50 #51 My Orders Page Added
  Components/GenericLayout/GenericLayout.js
  Components/Profile/MyOrders.js
  Components/Profile/Profile.js
  configs/KEYS.js
Labels: Enhancement: High

#57 Removed Reundancies of application and few touch ups
  Components/Footer/Footer.js
  Components/GenericLayout/GenericLayout.js
  Components/Header/Header.js
  Components/Notification/Notification.js
  Components/Profile/Profile.js
  Components/Subscriptions/Subscriptions.js
  Components/serviceitemtype/index.js
Labels: Bug: Trivial

#61 Fixed #58 #59 #60
  Components/Cart/Cart.js
  Components/HomeScreen/HomeScreen.js
  package-lock.json
  package.json
Labels: Bug: Minor, Enhancement: High

#62 Added Icons for each service on Homepage
  Components/HomeScreen/HomeScreen.js
Labels: Enhancement: Medium

#64 Fixed #63
  Components/Profile/MyOrders.js
Labels: Enhancement: Medium

#66 fixed #65
  __mocks__/@react-native-community/async-storage.js
  __tests__/Components/EditProfile.test.js
  __tests__/Components/Footer.test.js
  __tests__/Components/Header.test.js
  __tests__/Components/HomeScreen.test.js
  __tests__/Components/Profile.test.js
  __tests__/Components/__snapshots__/EditProfile.test.js.snap
  __tests__/Components/__snapshots__/Footer.test.js.snap
  __tests__/Components/__snapshots__/Header.test.js.snap
  __tests__/Components/__snapshots__/HomeScreen.test.js.snap
  __tests__/Components/__snapshots__/Profile.test.js.snap
  __tests__/global.js
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/Components/Auth/CreateUser.js.html
  coverage/lcov-report/Components/Auth/FirstAuthScreen.js.html
  coverage/lcov-report/Components/Auth/SignInScreen.js.html
  coverage/lcov-report/Components/Auth/index.html
  coverage/lcov-report/Components/Footer/Footer.js.html
  coverage/lcov-report/Components/Footer/index.html
  coverage/lcov-report/Components/Header/Header.js.html
  coverage/lcov-report/Components/Header/index.html
  coverage/lcov-report/Components/HomeScreen/HomeScreen.js.html
  coverage/lcov-report/Components/HomeScreen/index.html
  coverage/lcov-report/Components/Profile/EditProfile.js.html
  coverage/lcov-report/Components/Profile/MyOrders.js.html
  coverage/lcov-report/Components/Profile/Profile.js.html
  coverage/lcov-report/Components/Profile/index.html
  coverage/lcov-report/Components/ServiceSpecific/ServiceSpecific.js.html
  coverage/lcov-report/Components/ServiceSpecific/index.html
  coverage/lcov-report/Components/ServiceSpecific/styles.js.html
  coverage/lcov-report/Components/serviceitem/index.html
  coverage/lcov-report/Components/serviceitem/index.js.html
  coverage/lcov-report/Components/serviceitem/styles.js.html
  coverage/lcov-report/Components/serviceitemtype/index.html
  coverage/lcov-report/Components/serviceitemtype/index.js.html
  coverage/lcov-report/Components/serviceitemtype/styles.js.html
  coverage/lcov-report/assets/index.html
  coverage/lcov-report/assets/logo.png.html
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/configs/CacheManager.js.html
  coverage/lcov-report/configs/KEYS.js.html
  coverage/lcov-report/configs/firebase-init.js.html
  coverage/lcov-report/configs/index.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  package-lock.json
  package.json
Labels: Enhancement: High
